server:
  port: 8080
  url:

spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssafast?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ssafast
    password: 502502502

  #  data:
  #    mongodb:
  #      host: localhost
  #      port: 27017
  #      username: ssafast
  #      password: 502502502

  jpa:
    properties:
      hibernate:
        format_sql: True
jwt:
  secret: q84RqM8cXca0CHwl8uAji7DBa0riKquYsquZCZ+hihiO3UwAoAZ9YsUqrCyALgBbbr7MBXaugWAdXKfVn4s7qQ==
  refresh-token-validity-in-seconds: 1209600  # 14일
  access-token-validity-in-seconds: 43200     # 12시간